channels:
  - defaults
  - conda-forge

dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - notebook
  - jupyterlab
  - pip:
    - keras==2.1.2
    - tensorflow==1.4.0
    - livelossplot==0.1.6